set(ENV{VCPKG_DISABLE_METRICS} ON)

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

#set(VCPKG_PLATFORM_TOOLSET "v143")

if (PORT STREQUAL "openvr")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

if (PORT STREQUAL "apriltag")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
