cmake_minimum_required(VERSION 3.5)

set(binary_dir "${CMAKE_CURRENT_SOURCE_DIR}/build")
if (EXISTS ${binary_dir})
    message(STATUS "Cleaning ${binary_dir}")
    file(REMOVE_RECURSE ${binary_dir})
endif()

set(install_dir "${CMAKE_CURRENT_SOURCE_DIR}/install")
if (EXISTS ${install_dir})
    message(STATUS "Cleaning ${install_dir}")
    file(REMOVE_RECURSE ${install_dir})
endif()

foreach(idx RANGE 3 ${CMAKE_ARGC})
    set(argv ${CMAKE_ARGV${idx}})
    if (argv STREQUAL "CLEAN_DEPS")
        set(CLEAN_DEPS ON)
    elseif(argv STREQUAL "CLEAN_MODULES")
        set(CLEAN_MODULES ON)
    endif()
endforeach(idx)

if (CLEAN_DEPS)
    foreach(file "deps/build" "deps/install")
        set(file_path "${CMAKE_CURRENT_SOURCE_DIR}/${file}")
        if (EXISTS ${file_path})
            message(STATUS "Cleaning ${file_path}")
            file(REMOVE_RECURSE ${file_path})
        endif()
    endforeach(file)
endif()

if (CLEAN_MODULES)
    find_program(GIT_CMD git)
    message(STATUS "Cleaning submodules")
    execute_process(COMMAND ${GIT_CMD} submodule deinit -q -f "${CMAKE_CURRENT_SOURCE_DIR}/deps")
endif()
