set(binary_dir "${CMAKE_CURRENT_SOURCE_DIR}/build")
if (EXISTS ${binary_dir})
    message(STATUS "Cleaning ${binary_dir}")
    file(REMOVE_RECURSE ${binary_dir})
endif()

if (${CLEAN_DEPS})
    foreach(file "deps/build" "deps/install")
        set(file_path "${CMAKE_CURRENT_SOURCE_DIR}/${file}")
        if (EXISTS ${file_path})
            message(STATUS "Cleaning dep ${file_path}")
            file(REMOVE_RECURSE ${file_path})
        endif()
    endforeach(file)
endif()

if (${CLEAN_MODULES})
    find_program(GIT_CMD git)
    message(STATUS "Cleaning submodules")
    execute_process(COMMAND ${GIT_CMD} submodule deinit -q -f "${CMAKE_CURRENT_SOURCE_DIR}/deps")
endif()