set(binary_dir "${CMAKE_CURRENT_SOURCE_DIR}/build")
if (EXISTS ${binary_dir})
    message(STATUS "cleaning ${binary_dir}")
    file(REMOVE_RECURSE ${binary_dir})
endif()

if (${CLEAN_ALL_DEPS})
    set(deps_dirs apriltag openvr wxWidgets)
    foreach(dir ${deps_dirs})
        file(GLOB contents "${CMAKE_CURRENT_SOURCE_DIR}/deps/${dir}/*")
        foreach(file ${contents})
            if (EXISTS ${file})
                message(STATUS "cleaning ${file}")
                file(REMOVE_RECURSE ${file})
            endif()
        endforeach(file)
    endforeach(dir)
endif()